#!/usr/bin/env python3
"""
Generate a keyword index: which glossary terms appear in which paper sections.

Usage:
    python paper/check_glossary.py                  # print index + violations
    python paper/check_glossary.py --index-only     # just the concordance
    python paper/check_glossary.py --violations-only # just banned synonym hits

Reads: paper/glossary.md, paper/sections/*.md
Writes: paper/keyword_index.md (always regenerated)
"""

import re
import sys
from collections import defaultdict
from pathlib import Path


def parse_glossary(glossary_path: Path) -> tuple[dict, dict, dict]:
    """
    Parse glossary.md into:
      terms: {term_name: definition_snippet}
      banned: {banned_phrase: preferred_term}
      exemptions: {banned_phrase: [exempt_context_phrases]}

    EXEMPT lines suppress violations when the exempt phrase appears on the same line.
    They apply to all banned phrases from the most recent "Do not write:" block.
    Format in glossary: : EXEMPT: "phrase" (explanation)
    """
    text = glossary_path.read_text(encoding="utf-8")
    terms = {}
    banned = {}
    exemptions = {}

    current_term = None
    last_banned_phrases: list[str] = []
    for line in text.splitlines():
        # Bold term definition: **Term Name**
        m = re.match(r'^\*\*(.+?)\*\*\s*$', line)
        if m:
            current_term = m.group(1).strip()
            terms[current_term] = ""
            last_banned_phrases = []
            continue

        # "Do not write:" line captures banned synonyms
        if current_term and "Do not write:" in line:
            last_banned_phrases = []
            for phrase_match in re.finditer(r'"([^"]+)"', line):
                phrase = phrase_match.group(1).lower()
                banned[phrase] = current_term
                last_banned_phrases.append(phrase)
            continue

        # "EXEMPT:" line captures exemption contexts for the most recent banned phrases
        if current_term and "EXEMPT:" in line:
            for phrase_match in re.finditer(r'"([^"]+)"', line):
                exempt_phrase = phrase_match.group(1).lower()
                for banned_phrase in last_banned_phrases:
                    exemptions.setdefault(banned_phrase, []).append(exempt_phrase)
            continue

    return terms, banned, exemptions


def scan_section(
    section_path: Path, terms: dict, banned: dict, exemptions: dict
) -> tuple[dict, list]:
    """
    Scan a section file for term occurrences and banned synonym violations.

    Returns:
      found: {term_name: [line_numbers]}
      violations: [(line_number, banned_phrase, preferred_term)]

    Violations are suppressed when an exempt context phrase (from the glossary EXEMPT lines)
    appears on the same line as the banned phrase.
    """
    text = section_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    found = defaultdict(list)
    violations = []

    for i, line in enumerate(lines, 1):
        line_lower = line.lower()

        # Check for glossary terms
        for term_name in terms:
            # Match the term as a whole word (case-insensitive)
            pattern = re.escape(term_name.lower())
            if re.search(r'\b' + pattern + r'\b', line_lower):
                found[term_name].append(i)

        # Check for banned synonyms
        for banned_phrase, preferred in banned.items():
            pattern = re.escape(banned_phrase)
            if re.search(r'\b' + pattern + r'\b', line_lower):
                # Suppress if an exempt context phrase appears on the same line
                exempt = any(
                    ctx in line_lower
                    for ctx in exemptions.get(banned_phrase, [])
                )
                if not exempt:
                    violations.append((i, banned_phrase, preferred))

    return dict(found), violations


def generate_index(
    sections_dir: Path,
    glossary_path: Path,
    output_path: Path,
) -> tuple[str, list]:
    """
    Generate keyword_index.md and return (index_text, all_violations).
    """
    terms, banned, exemptions = parse_glossary(glossary_path)
    section_files = sorted(sections_dir.glob("*.md"))

    # term -> {section_name: [line_numbers]}
    index = defaultdict(dict)
    all_violations = []

    for sf in section_files:
        section_name = sf.stem  # e.g., "03_methods"
        found, violations = scan_section(sf, terms, banned, exemptions)

        for term, line_nums in found.items():
            index[term][section_name] = line_nums

        for line_num, phrase, preferred in violations:
            all_violations.append((sf.name, line_num, phrase, preferred))

    # Build index markdown
    lines = [
        "# Keyword Index",
        "",
        "Auto-generated by `check_glossary.py`. Do not edit manually.",
        "",
        "Shows which glossary terms appear in which sections (with line counts).",
        "",
        "---",
        "",
    ]

    for term in sorted(index.keys(), key=str.lower):
        sections_info = []
        for section_name in sorted(index[term].keys()):
            count = len(index[term][section_name])
            sections_info.append(f"{section_name} ({count})")
        lines.append(f"**{term}**: {', '.join(sections_info)}")
        lines.append("")

    # Terms with zero occurrences
    unused = [t for t in terms if t not in index]
    if unused:
        lines.append("---")
        lines.append("")
        lines.append("## Unused Terms")
        lines.append("")
        lines.append("Glossary terms not found in any section:")
        lines.append("")
        for t in sorted(unused, key=str.lower):
            lines.append(f"- {t}")
        lines.append("")

    index_text = "\n".join(lines)
    output_path.write_text(index_text, encoding="utf-8")

    return index_text, all_violations


def main():
    paper_dir = Path(__file__).parent
    sections_dir = paper_dir / "sections"
    glossary_path = paper_dir / "glossary.md"
    output_path = paper_dir / "keyword_index.md"

    if not glossary_path.exists():
        print(f"ERROR: {glossary_path} not found", file=sys.stderr)
        sys.exit(1)

    if not sections_dir.exists():
        print(f"ERROR: {sections_dir} not found", file=sys.stderr)
        sys.exit(1)

    index_only = "--index-only" in sys.argv
    violations_only = "--violations-only" in sys.argv

    index_text, violations = generate_index(sections_dir, glossary_path, output_path)

    if not violations_only:
        print(index_text)
        print(f"\nWritten to {output_path}")

    if not index_only:
        if violations:
            print(f"\n{'=' * 60}")
            print(f"BANNED SYNONYM VIOLATIONS ({len(violations)})")
            print(f"{'=' * 60}\n")
            for filename, line_num, phrase, preferred in sorted(violations):
                print(f"  {filename}:{line_num}: \"{phrase}\" → use \"{preferred}\"")
            print()
            sys.exit(1)
        else:
            print("\nNo banned synonym violations found.")


if __name__ == "__main__":
    main()
