<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brock Webb">
<meta name="dcterms.date" content="2026-03-01">
<meta name="keywords" content="genetic programming, symbolic regression, wrong-limit attractors, convergent series, search space, fitness engineering">

<title>The Evaluation Horizon Trap: Why Search Space Structure Dominates Fitness Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Evaluation Horizon Trap: Why Search Space Structure Dominates Fitness Design</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brock Webb </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Finite evaluation of an infinite-horizon process cannot distinguish a correct answer from one that merely appears correct within the evaluation horizon. We call these false matches wrong-limit attractors. They arise wherever finite evaluation meets infinite-horizon targets – in reinforcement learning as reward hacking, in language models as confabulation, in symbolic regression as spurious convergence.</p>
    <p>We study their dynamics in a controlled setting: genetic programming tasked with rediscovering the Leibniz series for π/4 from arithmetic primitives. Two fitness functions evaluate convergence across depths rather than pointwise accuracy; both rank Leibniz as optimal when present. With 4 terminals, 19 of 20 seeds discovered Leibniz (log-precision fitness). With 15 terminals at populations up to 5,000, none did. A partial recovery (2/5 seeds) appeared at 10x population and t=15, but not at t=10, t=12, or t=20. Seven fitness modifications and extended time failed to shift the phase transition boundary between t=8 and t=10.</p>
    <p>The bottleneck is not fitness quality but coverage: whether correct building blocks appear before wrong-limit attractors dominate. As primitives increase, the space of expressions consistent with the target within the evaluation horizon grows combinatorially while the target remains a single point. The traps are subtle – their trajectories fall within measurement resolution of the correct answer at every checkpoint. Fitness engineering, extended computation, and population scaling do not reliably compensate for a search space in which the correct structure is combinatorially outnumbered by indistinguishable impostors.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>genetic programming, symbolic regression, wrong-limit attractors, convergent series, search space, fitness engineering</p>
  </div>
</div>

</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Every AI system is evaluated within a finite horizon. Training runs end, test sets have boundaries, and context windows close. This is not a defect in any particular architecture. The constraint is structural, arising from how we build and test all of them. Any search process evaluated within a finite horizon will find outputs that look correct inside that horizon. Whether those outputs remain correct beyond it is a question that finite evaluation cannot answer.</p>
<p>You cannot close that gap by designing a better test. You can only manage it by constraining the search space. This paper demonstrates that mechanism, gives it a name, and shows through a controlled experiment what works and what does not.</p>
<p>We call these failures <em>wrong-limit attractors</em>: outputs of a search process that appear to converge toward a target value within the evaluation horizon but whose long-term behavior is unknown. They could plausibly converge to the target. They could converge to a nearby but different value. They could eventually diverge. Without carrying evaluation to the limit, we cannot distinguish these cases.</p>
<p>They are not overfitting: they genuinely appear to converge. They are not noise: they are structurally coherent. They are not evaluation function errors: the evaluation correctly ranks the right answer above them when both are present. Wrong-limit attractors arise because the gap between finite observation and infinite-horizon behavior is not closable by finite means. As the search space grows, outputs consistent with the target within the evaluation horizon multiply combinatorially while the actual target remains a single point. At some point, the difference between the target and a wrong-limit attractor’s trajectory may fall below the resolution of the evaluation instrument, and the distinction becomes unmeasurable. The problem lives in the space between that resolution floor and the evaluation horizon: deviations large enough to matter, too small to detect within the horizon.</p>
<p>We study this through a clean, controlled case: can genetic programming rediscover the Leibniz series for π/4 from arithmetic primitives alone?</p>
<p><span class="math display">\[\frac{\pi}{4} = \sum_{k=0}^{\infty} \frac{(-1)^k}{2k+1} = 1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \cdots\]</span></p>
<p>The series converges to π/4 but does so slowly, gaining roughly 3.32 bits of precision per decade of terms. Leibniz is an ideal laboratory: the target is known exactly, the search space is enumerable, the failure mode is quantifiable, and success or failure is binary. We develop two fitness functions that evaluate convergence behavior across evaluation depths rather than pointwise accuracy, motivated by an analogy to reaction kinetics developed in Section 6.1. Both correctly identify Leibniz as optimal when it is present. We demonstrate this in a controlled setting where the failure mode can be quantified exactly. The structural argument extends to any finite-horizon evaluation of infinite-horizon processes.</p>
<p>Discovery exhibits a sharp phase transition as the search space grows. With 4 arithmetic primitives, discovery is reliable: 19 of 20 seeds found Leibniz across all tested population sizes. With 15 primitives, discovery fails completely despite the fitness function still ranking Leibniz as optimal. Seven modifications to the fitness function all failed at 15 primitives. Increasing the population by 10x did not shift the failure boundary. Extending the time budget by 4x did not rescue discovery.</p>
<p>The bottleneck is not the fitness landscape, which places Leibniz at its global optimum. The bottleneck is coverage: the probability that the correct building blocks appear in the population before wrong-limit attractors dominate. After correcting an initial methodological confound in which the target expression was inadvertently seeded in the population (Section 4.1), all experiments use pure random initialization. The failure conditions are more instructive than the success.</p>
<p>This failure mode is not specific to genetic programming or to the Leibniz problem. Any system that evaluates process behavior within a finite horizon faces the same structural constraint.</p>
<p>In reinforcement learning, policies optimized over finite episodes can exploit the reward structure within the evaluation horizon without learning genuinely reliable behavior <span class="citation" data-cites="Amodei2016ConcreteProblems">(<a href="#ref-Amodei2016ConcreteProblems" role="doc-biblioref">Amodei et al., 2016</a>)</span>. In large language models, training against finite context windows creates the conditions for confabulation <span class="citation" data-cites="Ji2023Hallucination NIST2024AI600">(<a href="#ref-NIST2024AI600" role="doc-biblioref">Artificial Intelligence Risk Management Framework, 2024</a>; <a href="#ref-Ji2023Hallucination" role="doc-biblioref">Ji et al., 2023</a>)</span>. The resulting outputs appear well-formed and plausible within the training distribution but do not correspond to truth. In symbolic regression, pointwise fitness creates wrong-limit attractors for any problem involving convergence, stability, or asymptotic behavior. The common structure is that finite evaluation of infinite-horizon processes creates a space of outputs that are indistinguishable from the correct answer within the evaluation horizon. The lever that matters is not a better evaluation function but a more constrained search space.</p>
<p>Section 2 reviews related work on symbolic regression and process-level fitness design. Sections 3 and 4 describe the GP engine, fitness functions, and experimental design, including terminal set construction and the scaling grid. Section 5 presents results: the phase transition, wrong-limit attractor families, parsimony effects, and threshold sensitivity. Sections 6 and 7 discuss the kinetics connection, the confabulation analogy, implications for symbolic regression, and conclude.</p>
</section>
<section id="background-and-related-work" class="level1">
<h1>Background and Related Work</h1>
<section id="symbolic-regression" class="level2">
<h2 class="anchored" data-anchor-id="symbolic-regression">Symbolic Regression</h2>
<p>Symbolic regression searches for mathematical expressions that fit data, discovering both the functional form and its parameters simultaneously. Unlike conventional regression, which assumes a model structure and optimizes coefficients, symbolic regression explores the full space of compositions over a given operator and terminal set.</p>
<p><span class="citation" data-cites="Schmidt2009Distilling">Schmidt &amp; Lipson (<a href="#ref-Schmidt2009Distilling" role="doc-biblioref">2009</a>)</span> showed that GP-based symbolic regression could recover Hamiltonians and Lagrangians from experimental data. Their result was widely interpreted as evidence that symbolic regression extracts natural laws without domain knowledge. <span class="citation" data-cites="Hillar2012Comment">Hillar &amp; Sommer (<a href="#ref-Hillar2012Comment" role="doc-biblioref">2012</a>)</span> subsequently demonstrated that the fitness function implicitly encoded Hamilton’s equations, so that high-fitness expressions were Hamiltonians by construction. The “laws” were not discovered from scratch; the fitness measure already contained classical mechanics. This critique parallels our own injection confound (Section 4.1). Seeding the initial population with the target formula created the illusion of discovery; the formula was merely preserved through elitism.</p>
<p>Modern symbolic regression spans evolutionary <span class="citation" data-cites="Cranmer2023PySR">(<a href="#ref-Cranmer2023PySR" role="doc-biblioref">Cranmer, 2023</a>)</span>, transformer-based <span class="citation" data-cites="Valipour2021SymbolicGPT">(<a href="#ref-Valipour2021SymbolicGPT" role="doc-biblioref">Valipour et al., 2021</a>)</span>, neural-symbolic, generative flow <span class="citation" data-cites="Li2023GFlowNet">(<a href="#ref-Li2023GFlowNet" role="doc-biblioref">Li et al., 2023</a>)</span>, tree-search <span class="citation" data-cites="Kamienny2023MCTS Shojaee2023TPSR">(<a href="#ref-Kamienny2023MCTS" role="doc-biblioref">Kamienny et al., 2023</a>; <a href="#ref-Shojaee2023TPSR" role="doc-biblioref">Shojaee et al., 2023</a>)</span>, and equality saturation approaches <span class="citation" data-cites="Jiang2025EGGSR">(<a href="#ref-Jiang2025EGGSR" role="doc-biblioref">Jiang et al., 2025</a>)</span>. All of these systems optimize pointwise fitness: they minimize error between predicted and observed values at discrete (x, y) pairs. None address the problem class we consider, evaluating convergence properties of an infinite-horizon generating process against a known limit.</p>
</section>
<section id="fitness-design-for-convergent-processes" class="level2">
<h2 class="anchored" data-anchor-id="fitness-design-for-convergent-processes">Fitness Design for Convergent Processes</h2>
<p>The standard symbolic regression fitness is root-mean-square error between predicted and observed outputs. Pareto-based approaches add complexity as a second objective. Parsimony pressure (λ_p, a size penalty on expression trees), penalizing expression size, is the simplest form.</p>
<p>For infinite-horizon convergent processes, pointwise fitness is insufficient. A series that sums to a value near π/4 at T=10,000 terms would score well on pointwise accuracy but has no structural relationship to Leibniz. The fitness must instead evaluate how partial sums <em>behave</em> across evaluation depth. Does error decrease monotonically? Is the rate of improvement sustained? Does the precision gain follow a predictable scaling law?</p>
<p>Prior symbolic regression work does not address fitness design for this objective class. The closest analog is time-series forecasting, where models are evaluated on multi-step-ahead prediction quality rather than single-point accuracy. Both require evaluating trajectory behavior rather than endpoint accuracy, but the Leibniz problem evaluates convergence structure across geometric scales rather than sequential forecast accuracy.</p>
<p><span class="citation" data-cites="Abdusalamov2023Asymptotic">Abdusalamov et al. (<a href="#ref-Abdusalamov2023Asymptotic" role="doc-biblioref">2023</a>)</span> use symbolic regression to discover asymptotic series expansions for problems in mechanics, recovering convergent and divergent series from exact solutions. Their fitness is still pointwise: SR expressions are evaluated against sampled data, not against convergence properties of their partial sums. The Leibniz problem differs in that no target data exist; fitness must evaluate the summation process itself.</p>
</section>
<section id="wrong-limit-attractors" class="level2">
<h2 class="anchored" data-anchor-id="wrong-limit-attractors">Wrong-Limit Attractors</h2>
<p>The symbolic regression literature extensively discusses <em>bloat</em>: the tendency of GP to produce increasingly complex expressions that overfit without improving generalization <span class="citation" data-cites="Poli2008FieldGuide">(<a href="#ref-Poli2008FieldGuide" role="doc-biblioref">Poli et al., 2008a</a>)</span>. Our failure mode is distinct. Wrong-limit attractors are structurally <em>simpler</em> than the correct answer and converge to a finite limit. They score well because their limit happens to fall near π/4 within the evaluation horizon.</p>
<p>Wrong-limit attractors exploit a fundamental asymmetry. A large class of rational functions P(k)/Q(k) have partial sums converging to finite values near any target. Only one expression is Leibniz. As the terminal set grows, the density of accessible wrong-limit attractors increases combinatorially. The correct answer remains a single point in the expression space. The fitness function correctly ranks Leibniz above any wrong-limit attractor when both are present. However, the search must first assemble the correct building blocks, and this becomes exponentially less likely as the search space expands.</p>
<p>The concept is related to deceptive attractors in genetic algorithms <span class="citation" data-cites="Goldberg1989GA Deb1993Deceptive">(<a href="#ref-Deb1993Deceptive" role="doc-biblioref">Deb &amp; Goldberg, 1993</a>; <a href="#ref-Goldberg1989GA" role="doc-biblioref">Goldberg, 1989</a>)</span>. A deceptive attractor is a suboptimal solution toward which search is drawn because low-order building block information (schema) points away from the global optimum. In deceptive fitness landscapes, low-order schema information draws search toward suboptimal solutions. Deceptive attractors are defined by misleading fitness gradients in genotype space. Wrong-limit attractors are defined by indistinguishable behavior within a finite evaluation horizon. The deception is in the process output, not the search space topology. To our knowledge, no prior work analyzes this failure mode as distinct from bloat or overfitting in symbolic regression.</p>
<p>A related question is how large a GP population must be for selection to reliably propagate correct building blocks. Population-sizing theory for GP <span class="citation" data-cites="Sastry2005PopulationSizing">(<a href="#ref-Sastry2005PopulationSizing" role="doc-biblioref">Sastry, 2005</a>)</span> shows that the required population grows with problem difficulty, bloat, and the number of building blocks that must be simultaneously present. We return to this framework in Section 6.2 when analyzing why population increases fail to rescue discovery at large terminal counts.</p>
</section>
<section id="the-evaluation-horizon-trap" class="level2">
<h2 class="anchored" data-anchor-id="the-evaluation-horizon-trap">The Evaluation Horizon Trap</h2>
<p>Any finite evaluation horizon T_max creates a class of expressions indistinguishable from the correct answer within that horizon. Extending T_max does not eliminate this class; it shifts the attractor landscape. At T_max = 10,000, an expression converging to a value near but not equal to π/4 scores nearly identically to Leibniz. At T_max = 100,000, that expression would be distinguishable. New attractors converging to values even closer to π/4 would take its place.</p>
<p>The evaluation horizon trap is not a limitation of our specific fitness function. The trap is a structural property of any finite evaluation of infinite-horizon processes. We document it as a constraint on fitness-guided search in this problem class.</p>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="expression-representation" class="level2">
<h2 class="anchored" data-anchor-id="expression-representation">Expression Representation</h2>
<p>Candidate series are represented as expression trees over a set of operators and terminals. Each tree defines a function f(k) that maps the integer index k to a term value. The partial sum at depth T is:</p>
<p><span class="math display">\[S(T) = \sum_{k=0}^{T-1} f(k)\]</span></p>
<p>For Leibniz, f(k) = (-1)^k / (2k+1), and S(T) → π/4 as T → ∞.</p>
<p><em>Operators.</em> Binary operators {+, -, ×, ÷, ^} and unary negation. Division by zero returns 1.0 (safe division). The power operator rounds its exponent to the nearest integer before evaluation, constraining the search to integer powers. Power overflow (|result| &gt; 10^6) returns 1.0.</p>
<p><em>Terminals.</em> A configurable set always containing the variable k and constants. The minimal set is {k, 1, -1, 2}. Expanded sets add integers following a deterministic pattern described in Section 4.3.</p>
<p>To make the search concrete, consider the target f(k) = (-1)^k / (2k+1). The GP must discover three structural building blocks and compose them correctly. First, oscillation: (-1)^k produces the alternating sign, requiring the terminal -1, the variable k, and the power operator composed as pow(-1, k). Second, odd denominator: 2k+1 produces 1, 3, 5, 7, …, requiring the terminals 2 and 1, the variable k, and multiplication and addition composed as add(mul(2, k), 1). Third, division: the oscillating numerator divided by the growing denominator produces terms of decreasing magnitude with alternating sign.</p>
<p>With the minimal terminal set {k, 1, -1, 2}, these are essentially the only building blocks available. The GP has limited options for constructing oscillation (only (-1)^k works with the available terminals) and limited options for the denominator (only 2k+1 uses all remaining terminals meaningfully). This constraint is why discovery succeeds: the correct answer is one of few well-formed expressions in the search space.</p>
<p>With 15 terminals, the picture changes. Oscillation can be constructed from (-1)^k, (-3)^k, or various other bases. Denominators can be any polynomial or rational function of k. The number of structurally distinct well-formed expressions grows combinatorially, and most of them are wrong-limit attractors.</p>
</section>
<section id="evolutionary-search" class="level2">
<h2 class="anchored" data-anchor-id="evolutionary-search">Evolutionary Search</h2>
<p>We use standard GP with ramped half-and-half initialization (depths 2–5), tournament selection (k=7), subtree crossover (P=0.70), subtree mutation (P=0.20), reproduction (P=0.10), and elitism (top 5 preserved). Population sizes range from 1,000 to 10,000 depending on the experiment. Time budgets vary by experiment (Section 4.2).</p>
<p>Trees are constrained to at most 30 nodes. The depth limit of 6 applies during initialization; genetic operators enforce only the node count constraint. Mutation subtrees are generated with maximum depth 3. A diversity injection mechanism replaces the worst 100 individuals with fresh random trees when the top 20 fitness values become identical to six decimal places. This prevents premature convergence to a single attractor.</p>
<p>No domain-specific operators (such as “alternating sign” or “odd number generator”) are included. The search must assemble oscillating convergent behavior from general-purpose arithmetic alone.</p>
<p><em>Stopping criteria.</em> Each run terminates when the time budget is exhausted. The log-precision fitness also triggers early stopping after 100 generations of no improvement once the best expression exceeds 13.0 bits of precision with stable monotonicity. Time budgets vary by experiment (Section 4.2).</p>
<p><em>Discovery criterion.</em> An expression counts as a discovery if each term matches the Leibniz series to within 10^-6 absolute error. We evaluate f(k) for k = 0, 1, …, 19 and compare against the precomputed Leibniz values (-1)^k/(2k+1). The tolerance accommodates floating-point arithmetic. The question is whether the expression produces the same term sequence as Leibniz, not whether it achieves a fitness threshold. This criterion is applied post-hoc after each run completes, independent of the fitness score.</p>
</section>
<section id="fitness-functions" class="level2">
<h2 class="anchored" data-anchor-id="fitness-functions">Fitness Functions</h2>
<section id="convergence-aware-fitness-first-order" class="level3">
<h3 class="anchored" data-anchor-id="convergence-aware-fitness-first-order">Convergence-Aware Fitness (First-Order)</h3>
<p>The convergence-aware fitness rewards expressions whose partial sums approach π/4 with decreasing error at successive evaluation checkpoints T ∈ {10, 50, 200, 1000, 5000}.</p>
<p><span class="math display">\[\text{fitness}_{\text{conv}} = \text{accuracy} + \alpha \cdot \text{convergence\_bonus} - \lambda_p \cdot \text{nodes}\]</span></p>
<p>where accuracy = -mean(|S(T) - π/4|) across checkpoints, convergence_bonus = fraction of consecutive checkpoint pairs where error decreases by at least 5%, and nodes is the expression tree size (parsimony pressure, λ_p, a size penalty on expression trees). Weights: α = 0.05, λ_p = 0.005.</p>
<p>We label this a “first-order” fitness by analogy to chemical reaction kinetics: first-order asks whether error is shrinking, second-order asks whether the rate of precision gain is sustained across scales. Section 6.1 develops this parallel. The label reflects the simplest convergence question. Many processes exhibit shrinking error over some range. The convergence bonus rewards shrinkage across consecutive checkpoint pairs, but any monotonically converging series, regardless of its limit, can score well.</p>
</section>
<section id="log-precision-fitness-second-order" class="level3">
<h3 class="anchored" data-anchor-id="log-precision-fitness-second-order">Log-Precision Fitness (Second-Order)</h3>
<p>The log-precision fitness evaluates partial sums at 11 checkpoints spanning three decades: T ∈ {5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000}. The denser checkpoint set (compared to the five checkpoints used by the convergence-aware fitness) provides finer-grained measurement of precision gain rate and extends the evaluation horizon to T = 10,000. The specific checkpoint values influence which attractors are detectable. An attractor that matches the target at most checkpoints but diverges at others can appear competitive (Appendix A.2.3). The fitness measures precision in bits:</p>
<p><span class="math display">\[\text{prec}(T) = -\log_2 |S(T) - \pi/4|\]</span></p>
<p>The quantity -log₂(|error|) has the same mathematical form as Shannon’s self-information, but it is not entropy in the information-theoretic sense. The quantity measures precision of a single estimate, not uncertainty over a distribution. Leibniz at T=5 has precision 4.34 bits; at T=10,000, 15.29 bits.</p>
<p>The fitness combines three terms:</p>
<p><span class="math display">\[\text{fitness}_{\text{prec}} = w_1 \frac{\text{prec}(T_{\max})}{50} + w_2 \cdot \text{monotonicity} + w_3 \frac{\text{mean\_rate}}{5} - \lambda_p \cdot \text{nodes}\]</span></p>
<p>where monotonicity = fraction of consecutive checkpoints with ≥ 0.5 bit gain, and mean_rate = precision gain in bits per decade of summation depth. The 0.5 bit gain threshold is calibrated to Leibniz’s natural gain rate (see Section 5.6). Weights: w_1 = 0.02, w_2 = 0.04, w_3 = 0.03, λ_p = 0.005. These weights were set by hand to balance the three fitness terms. Section 5.6 tests sensitivity to the monotonicity threshold but not to the weights themselves.</p>
<p>By the same kinetics analogy, this asks a “second-order” question: <em>is precision gain sustained at a constant rate across scales?</em> Leibniz gains log₂(10) ≈ 3.32 bits per decade. On a log-log plot, this is a straight line. The constant rate is the signature of second-order kinetics (Section 6.1). Fewer processes satisfy this criterion than satisfy first-order error shrinkage.</p>
</section>
<section id="why-the-second-order-question-is-more-selective" class="level3">
<h3 class="anchored" data-anchor-id="why-the-second-order-question-is-more-selective">Why the Second-Order Question Is More Selective</h3>
<p>Many series exhibit decreasing error. Rational functions like 5/((6+4k)(k-2)) converge monotonically to a finite limit and score well on the convergence-aware fitness. Their precision gain rate is not constant across scales: it accelerates as the series approaches its limit, then plateaus.</p>
<p>Leibniz is unusual: its precision gain rate is constant because its error decays as 1/(2T+1). Plotting 1/error vs T yields a straight line, the integrated form of a second-order rate law. The log-precision fitness selects for this specific convergence structure, making it more discriminating than the convergence-aware fitness. Empirically, the log-precision fitness discovers Leibniz at population 1,000 (5/5 seeds), while the convergence-aware fitness requires population 2,000 for the same reliability.</p>
</section>
</section>
</section>
<section id="experimental-design" class="level1">
<h1>Experimental Design</h1>
<section id="the-injection-confound" class="level2">
<h2 class="anchored" data-anchor-id="the-injection-confound">The Injection Confound</h2>
<p>Early experiments (v2) seeded the initial population with a copy of the Leibniz expression tree. Both fitness functions reported 1.0/5 discovery, but subsequent analysis showed this was an artifact. The injected tree survived through elitism, never being lost to selection pressure. The tree was <em>retained</em>, not <em>discovered</em>.</p>
<p>We made this error, caught it, and corrected it. All results in this paper (v3 onward) use pure random initialization with no injection.</p>
<p>We document the confound here because it mirrors a known failure mode. <span class="citation" data-cites="Hillar2012Comment">Hillar &amp; Sommer (<a href="#ref-Hillar2012Comment" role="doc-biblioref">2012</a>)</span> showed that <span class="citation" data-cites="Schmidt2009Distilling">Schmidt &amp; Lipson (<a href="#ref-Schmidt2009Distilling" role="doc-biblioref">2009</a>)</span> implicitly encoded the answer in the search structure, creating the illusion of emergent discovery. Our injection confound is the same class of error: when the target is present in the initial population, survival through elitism is indistinguishable from discovery.</p>
</section>
<section id="clean-protocol-v3" class="level2">
<h2 class="anchored" data-anchor-id="clean-protocol-v3">Clean Protocol (v3)</h2>
<p>All v3 experiments use ramped half-and-half initialization with no injection. Each configuration is evaluated across five seeds (42, 7, 137, 2718, 31415). The function set (Section 3.1) is held constant across all experiments: binary operators {+, -, ×, ÷, ^} and unary negation.</p>
<p>Time budgets are pragmatic compute constraints, not theoretically motivated. Minimal-terminal runs allocate 360 seconds per seed, with a 1,800-second total budget per configuration. Scaling grid runs allocate 1,800 seconds per seed, with a 10,800-second total budget per cell. An extended run at t=10 and pop=5,000 allocated 7,200 seconds per seed, four times the standard budget. 1.0/5 seeds found Leibniz under the extended budget, the same seed (val=7) that succeeded under the standard budget. The time budget is not the binding constraint at t=10.</p>
<p>An expression counts as a discovery if its terms match the Leibniz series term by term. We compute f(k) for k = 0, …, 19 and compare against precomputed Leibniz values (-1)^k/(2k+1). A tolerance of 10^-6 per term accommodates floating-point arithmetic (Section 3.2).</p>
</section>
<section id="terminal-set-construction" class="level2">
<h2 class="anchored" data-anchor-id="terminal-set-construction">Terminal Set Construction</h2>
<p>The GP primitive set is held constant across all experiments. The table below lists operators and their safe-evaluation behavior.</p>
<p><strong>Table 1:</strong> GP operator set and safe-evaluation behavior. Safe division and power overflow return implicit constant terminals.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Value</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Binary operators</td>
<td>+, -, ×, ÷, ^</td>
<td>Standard arithmetic</td>
</tr>
<tr class="even">
<td>Unary operators</td>
<td>neg</td>
<td>Negation</td>
</tr>
<tr class="odd">
<td>Safe division (÷ when |denominator| ≤ 10^-10)</td>
<td>returns 1.0</td>
<td>Implicit constant; acts as additional terminal</td>
</tr>
<tr class="even">
<td>Power overflow (|result| &gt; 10^6)</td>
<td>returns 1.0</td>
<td>Implicit constant; acts as additional terminal</td>
</tr>
<tr class="odd">
<td>Power exponent</td>
<td>Rounded to nearest integer</td>
<td>Constrains search to integer powers</td>
</tr>
</tbody>
</table>
<p>Safe division returns 1.0 when the denominator is at or below 10^-10. Power overflow returns 1.0 when the result magnitude exceeds 10^6. Both values act as implicit additional terminals in the search space. An expression that triggers either condition at certain k values uses 1.0 as a fallback constant. Researchers counting available terminals should account for these implicit constants. Because 1.0 is already in the base terminal set at all sizes, the implicit constants from safe division and power overflow do not increase the effective terminal count.</p>
<p>At each size N, terminal sets are constructed deterministically. The base set {k, 1, -1, 2} is always present, ensuring Leibniz is constructible regardless of the terminal count. Additional integers follow the pattern 3, -2, 4, -3, 5, -4, …, alternating positive and negative with no zero and no duplicates of base terminals. The alternating sign pattern ensures both positive and negative values are available at every terminal count. Additional terminals provide alternative construction paths for the oscillating numerator and odd denominator, not inert noise.</p>
<p>This construction controls for primitive availability. The experiment isolates the effect of search space expansion on discovery rate, not whether the correct building blocks exist.</p>
<p><strong>Table 2:</strong> Terminal set construction at each size N. The base set {k, 1, -1, 2} is always present.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>N</th>
<th>Terminal Set</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>{k, 1, -1, 2}</td>
</tr>
<tr class="even">
<td>6</td>
<td>{k, 1, -1, 2, 3, -2}</td>
</tr>
<tr class="odd">
<td>8</td>
<td>{k, 1, -1, 2, 3, -2, 4, -3}</td>
</tr>
<tr class="even">
<td>10</td>
<td>{k, 1, -1, 2, 3, -2, 4, -3, 5, -4}</td>
</tr>
<tr class="odd">
<td>12</td>
<td>{k, 1, -1, 2, 3, -2, 4, -3, 5, -4, 6, -5}</td>
</tr>
<tr class="even">
<td>15</td>
<td>{k, 1, -1, 2, 3, -2, 4, -3, 5, -4, 6, -5, 7, -6, 8}</td>
</tr>
<tr class="odd">
<td>20</td>
<td>{k, 1, -1, 2, 3, -2, 4, -3, 5, -4, 6, -5, 7, -6, 8, -7, 9, -8, 10, -9}</td>
</tr>
</tbody>
</table>
</section>
<section id="scaling-grid" class="level2">
<h2 class="anchored" data-anchor-id="scaling-grid">Scaling Grid</h2>
<p>The scaling grid crosses seven terminal counts (N = 4, 6, 8, 10, 12, 15, 20) with four population sizes (1,000, 2,000, 5,000, 10,000). Five seeds per cell yield 140 individual runs. All runs use log-precision fitness; time budgets are specified in Section 4.2.</p>
<p>The design answers two questions. First, can increasing population size compensate for expanding terminal sets? Second, where is the boundary beyond which no tested population size achieves reliable discovery?</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="discovery-under-minimal-terminals" class="level2">
<h2 class="anchored" data-anchor-id="discovery-under-minimal-terminals">Discovery Under Minimal Terminals</h2>
<p>With the minimal terminal set {k, 1, -1, 2} and no injection, the log-precision fitness achieves 5/5 discovery across five seeds. The convergence-aware fitness achieves 2/5 at population 1,000 and 5/5 at population 2,000. Total runtime for the complete log-precision run across all five seeds was 369.9 seconds.</p>
<p><strong>Table 3:</strong> Discovery rates under minimal terminals (N=4) by fitness function and population size.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fitness</th>
<th>Pop</th>
<th>Seeds Found</th>
<th>Mean Generations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Log-precision</td>
<td>1,000</td>
<td>5/5</td>
<td>2981.0</td>
</tr>
<tr class="even">
<td>Convergence-aware</td>
<td>1,000</td>
<td>2/5</td>
<td>n/a</td>
</tr>
<tr class="odd">
<td>Convergence-aware</td>
<td>2,000</td>
<td>5/5</td>
<td>n/a</td>
</tr>
</tbody>
</table>
<p>All discovered expressions are algebraically equivalent to (-1)^k / (2k+1), verified identical at k=100,000 with zero divergence. The structural variants that appear across seeds are shown below.</p>
<p><strong>Table 4:</strong> Structural variants of the Leibniz series discovered across five seeds.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Seed</th>
<th>Expression</th>
<th>Nodes</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>42</td>
<td>(-(-1^k)) / ((-k) - (k - -1))</td>
<td>11</td>
<td>bloated form</td>
</tr>
<tr class="even">
<td>7</td>
<td>(-(-1^k)) / ((-1 - k) - k)</td>
<td>10</td>
<td>bloated form</td>
</tr>
<tr class="odd">
<td>137</td>
<td>(-(-1^k)) / ((-1 - k) - k)</td>
<td>10</td>
<td>same form as seed 7</td>
</tr>
<tr class="even">
<td>2718</td>
<td>(-1^k) / (k + (1 + k))</td>
<td>9</td>
<td>canonical minimal form</td>
</tr>
<tr class="odd">
<td>31415</td>
<td>(-1^k) / ((k × 2) - -1)</td>
<td>9</td>
<td>canonical minimal form</td>
</tr>
</tbody>
</table>
<p>The canonical 9-node form (-1)^k / (2k+1) is not always found: bloated algebraic equivalents appear in 3/5 seeds. Parsimony pressure at λ_p = 0.005 is insufficient to drive canonical form but does not impair discovery. Increasing parsimony to λ_p ≥ 0.01 destroys discovery entirely (Section 5.4).</p>
</section>
<section id="failure-under-expanded-terminals" class="level2">
<h2 class="anchored" data-anchor-id="failure-under-expanded-terminals">Failure Under Expanded Terminals</h2>
<p>With 15 terminals at population 1,000, no seeds find Leibniz (0/5). The failure modes split into two categories: trivial collapse to constants (4/5 seeds) and convergence to a wrong-limit attractor (1/5 seeds). Seeds 7 and 31415 collapsed to the constant 0, seed 137 to a small constant expression, and seed 2718 to a low-precision rational function (4.80 bits at T=10,000). Wrong-limit attractors become the dominant failure mode at larger terminal counts and populations. At t=20 with pop=10,000, all five seeds converged to a power-law decay family (Appendix A.3).</p>
<p>Seed 42 produced the strongest wrong-limit attractor: 5/((6+4k)(k-2)), which achieves 15.93 bits of precision at T=10,000, exceeding Leibniz’s 15.29 bits, with perfect monotonicity. This expression is not Leibniz. Within the evaluation horizon, its partial sums converge to a value that appears closer to π/4 than Leibniz. At T→∞, Leibniz converges exactly while this attractor converges to a different value.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fig2_precision_vs_T.png" class="img-fluid figure-img"></p>
<figcaption>Log-precision trajectories for the Leibniz series and the strongest wrong-limit attractor</figcaption>
</figure>
</div>
<p><strong>Figure 1:</strong> Log-precision trajectories for the Leibniz series and the strongest wrong-limit attractor (seed 42, 15 terminals). The attractor exceeds Leibniz precision within the evaluation horizon (T &lt;= 10,000) but converges to a different limit.</p>
</section>
<section id="the-scaling-boundary" class="level2">
<h2 class="anchored" data-anchor-id="the-scaling-boundary">The Scaling Boundary</h2>
<p>The 7 × 4 scaling grid reveals a phase transition between t=8 and t=10 for all population sizes tested. Discovery results across the full grid are as follows.</p>
<p><strong>Table 5:</strong> Discovery rate (seeds found / 5) across terminal set sizes and population sizes. The phase transition between t=8 and t=10 holds across all population sizes.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>t (terminals)</th>
<th>pop=1000</th>
<th>pop=2000</th>
<th>pop=5000</th>
<th>pop=10000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>5/5</td>
<td>4/5</td>
<td>5/5</td>
<td>5/5</td>
</tr>
<tr class="even">
<td>6</td>
<td>1/5</td>
<td>2/5</td>
<td>1/5</td>
<td>1/5</td>
</tr>
<tr class="odd">
<td>8</td>
<td>1/5</td>
<td>1/5</td>
<td>1/5</td>
<td>0/5</td>
</tr>
<tr class="even">
<td>10</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
</tr>
<tr class="odd">
<td>12</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
</tr>
<tr class="even">
<td>15</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
<td>2/5</td>
</tr>
<tr class="odd">
<td>20</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
<td>0/5</td>
</tr>
</tbody>
</table>
<p>At t=4, discovery is reliable across all population sizes. At t=6 and t=8, success drops but remains nonzero. At t=10 and above, discovery fails completely except for one anomaly: at t=15 with pop=10,000, 2/5 seeds succeed. This partial recovery is absent at t=10, t=12, and t=20. We do not have a mechanistic account of this non-monotonicity.</p>
<p>The boundary between t=8 and t=10 holds for all population sizes tested. Increasing population from 1,000 to 10,000 does not shift this boundary. Larger populations provide marginal gains at t=6 and t=8 and produce the anomalous partial recovery at t=15, but the t=10 wall remains intact. This pattern is consistent with a coverage limitation rather than a fitness landscape limitation.</p>
</section>
<section id="size-penalty" class="level2">
<h2 class="anchored" data-anchor-id="size-penalty">Size Penalty</h2>
<p>GP parsimony pressure penalizes larger expression trees by subtracting λ_p × (node count) from fitness. This size penalty keeps solutions simple but creates a ceiling on viable tree complexity.</p>
<p><strong>Table 6:</strong> Effect of parsimony pressure on discovery. The transition from full discovery to complete failure occurs between lambda_p = 0.005 and lambda_p = 0.01.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>λ_p</th>
<th>Seeds Found</th>
<th>Dominant Form</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.005 (baseline)</td>
<td>5/5</td>
<td>9–11 node Leibniz equivalents</td>
<td>Working</td>
</tr>
<tr class="even">
<td>0.01</td>
<td>0/5</td>
<td>3-node zero constants (k-k, 1+-1)</td>
<td>Penalty dominates</td>
</tr>
<tr class="odd">
<td>0.02</td>
<td>0/5</td>
<td>1-node constant (-1)</td>
<td>Leibniz ejected from top 10%</td>
</tr>
<tr class="even">
<td>0.05</td>
<td>0/5</td>
<td>1-node constant (-1)</td>
<td>Fitness ordering inverted</td>
</tr>
</tbody>
</table>
<p>The transition is sharp. At λ_p = 0.005, the 9-node Leibniz tree scores 0.021021 fitness. At λ_p = 0.01, the same tree scores -0.023979. The score is still nominally better than the zero-constant attractor at -0.029861, but the margin is too small for selection pressure to overcome the initialization disadvantage within the time budget.</p>
<p>The log-precision fitness terms (w_1·ti + w_2·mono + w_3·rate) sum to 0.066021 for a Leibniz expression. At 9 nodes and λ_p=0.005, the parsimony penalty is λ_p × 9 &lt; 0.066021, which requires λ_p &lt; 0.0073 for discovery to succeed. The baseline operates near but below this ceiling.</p>
<p>This threshold sensitivity is consistent with prior findings that parsimony pressure has a narrow effective range. Too weak and it fails to control bloat. Too strong and it collapses the population to trivial solutions <span class="citation" data-cites="Poli2008ParsimonyEasy Soule1998CodeGrowth">(<a href="#ref-Poli2008ParsimonyEasy" role="doc-biblioref">Poli et al., 2008b</a>; <a href="#ref-Soule1998CodeGrowth" role="doc-biblioref">Soule &amp; Foster, 1998</a>)</span>. Our contribution is the quantitative demonstration of the crossover point where the Leibniz tree’s fitness falls below the zero-constant attractor.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fig3_parsimony_collapse.png" class="img-fluid figure-img"></p>
<figcaption>Fitness score as a function of parsimony coefficient for the 9-node Leibniz tree and the 3-node zero-constant attractor</figcaption>
</figure>
</div>
<p><strong>Figure 2:</strong> Fitness score as a function of parsimony coefficient (lambda_p) for the 9-node Leibniz tree and the 3-node zero-constant attractor. The crossover at lambda_p approximately 0.0110 marks where the zero-constant becomes fitter than Leibniz.</p>
</section>
<section id="fitness-modifications-cannot-rescue-large-terminal-sets" class="level2">
<h2 class="anchored" data-anchor-id="fitness-modifications-cannot-rescue-large-terminal-sets">Fitness Modifications Cannot Rescue Large Terminal Sets</h2>
<p>We tested seven modifications to the log-precision fitness on the 15-terminal configuration. None achieved reliable discovery.</p>
<p><strong>Table 7:</strong> Fitness function modifications tested on the 15-terminal configuration. No modification achieved reliable discovery.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Modification</th>
<th>Seeds Found</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Extended checkpoints</td>
<td>0/5</td>
<td>Additional T values beyond 10,000</td>
</tr>
<tr class="even">
<td>Large-T penalty w=0.1</td>
<td>1/5</td>
<td>Penalizes series that plateau before T_max</td>
</tr>
<tr class="odd">
<td>Large-T penalty w=0.5</td>
<td>0/5</td>
<td>Penalty too heavy, kills borderline expressions</td>
</tr>
<tr class="even">
<td>Rate consistency</td>
<td>0/5</td>
<td>Penalizes deviation from constant bits/decade</td>
</tr>
<tr class="odd">
<td>Pure gradient magnitude</td>
<td>0/5</td>
<td>Rewards only precision gain rate, ignores terminal value</td>
</tr>
<tr class="even">
<td>Hybrid scalar×uniformity</td>
<td>0/5</td>
<td>Combined rate and uniformity signal</td>
</tr>
<tr class="odd">
<td>Min-component bottleneck</td>
<td>0/5</td>
<td>Requires all fitness terms above threshold</td>
</tr>
</tbody>
</table>
<p>The alpha parameter sweep (reducing α from 1.0 to 0.5 in the convergence-aware fitness) produced 4/5 on the minimal terminal set, comparable to the baseline. No modification achieved better than 1/5 on 15 terminals.</p>
<p>The consistent failure confirms the diagnosis: the bottleneck is coverage, not fitness landscape quality. The fitness correctly ranks Leibniz as optimal when Leibniz-equivalent subtrees are present in the population. Presence requires the population to contain the right building blocks, and the probability of assembling them decreases sharply with terminal set size.</p>
<p>We also ran the convergence-aware fitness at t=10 and population 5,000 with 7,200 seconds per seed, four times the standard budget. Only 1.0 of 5 seeds found Leibniz, the same seed (val=7) that succeeded under the standard budget. The remaining four seeds did not find Leibniz-equivalent expressions. Extending the time budget by a factor of four does not rescue discovery at t=10.</p>
</section>
<section id="threshold-sensitivity" class="level2">
<h2 class="anchored" data-anchor-id="threshold-sensitivity">Threshold Sensitivity</h2>
<p>The log-precision fitness uses a monotonicity threshold (MIN_GAIN) that defines how many bits of precision gain a checkpoint pair must show to count as monotonically improving. The baseline value of 0.5 bits was a design choice. We tested whether discovery rates depend on this threshold.</p>
<p><strong>Table 8:</strong> Log-precision monotonicity threshold sensitivity at t=4, pop=1,000. Leibniz gains approximately 1.0 bit per checkpoint step.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>MIN_GAIN (bits)</th>
<th>Seeds Found</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>2.0/5</td>
<td>Too permissive: wrong-limit attractors achieve full monotonicity credit</td>
</tr>
<tr class="even">
<td>0.5 (baseline)</td>
<td>5/5</td>
<td>Below Leibniz’s natural gain rate</td>
</tr>
<tr class="odd">
<td>1.0</td>
<td>1.0/5</td>
<td>At Leibniz’s gain rate: Leibniz barely qualifies</td>
</tr>
<tr class="even">
<td>2.0</td>
<td>0.0/5</td>
<td>Above Leibniz’s gain rate: fitness collapses to trivial constants</td>
</tr>
</tbody>
</table>
<p>The threshold is not a free parameter. It must be set below the target process’s natural precision gain rate. Leibniz gains approximately 1.0 bit per checkpoint step. At MIN_GAIN=0.5, the threshold is comfortably below this rate, and all seeds succeed. At MIN_GAIN=1.0, Leibniz itself barely satisfies the criterion, and discovery drops to 1.0/5. At MIN_GAIN=2.0, Leibniz never achieves the required gain, the W_2 (monotonicity) term contributes zero, and the fitness collapses to trivial zero-constant expressions. At the phase transition boundary (t=6), reducing MIN_GAIN to 0.1 did not change the discovery rate (1.0/5), suggesting the threshold matters only in the regime where coverage is sufficient.</p>
<p>The convergence-aware fitness threshold (5% error reduction between checkpoints) is less sensitive. Varying the threshold from 1% to 20% produced discovery rates between 2/5 and 3/5, within noise for a five-seed sample.</p>
<p>The threshold must be set below the target process’s natural gain rate. The threshold is constrained by the problem, not freely tunable.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>We first analyze the convergence structure that makes Leibniz detectable (6.1), then generalize the discovery mechanism (6.2). Sections 6.3 and 6.4 draw the analogy to broader AI systems and identify implications for symbolic regression.</p>
<section id="second-order-kinetics-connection" class="level2">
<h2 class="anchored" data-anchor-id="second-order-kinetics-connection">Second-Order Kinetics Connection</h2>
<p>Leibniz’s error decays as 1/(2T+1), algebraically 1/T behavior. Plotting 1/error versus T yields a straight line. In chemical kinetics, this is the signature of a second-order reaction: the rate depends on the product of two concentrations, or the square of one.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fig4_second_order_kinetics.png" class="img-fluid figure-img"></p>
<figcaption>Reciprocal error versus evaluation depth T for the Leibniz series</figcaption>
</figure>
</div>
<p><strong>Figure 3:</strong> Reciprocal error (1/|S(T) - pi/4|) versus evaluation depth T for the Leibniz series. The linear relationship confirms second-order convergence structure. The computed values (slope approximately 2) track the theoretical bound 2T+1 with a constant offset due to the alternating series remainder.</p>
<p>The parallel is structural, not rigorous; we do not claim the kinetics framework predicts convergence rates for arbitrary series. Each Leibniz term’s correction depends on two interacting quantities: the position k, which determines the magnitude 1/(2k+1), and the alternating sign (-1)^k, which determines the direction. A process depending on only one quantity would exhibit exponential (first-order) convergence. The interaction of two quantities produces 1/T convergence, fundamentally slower but with a distinctive constant-rate signature on a log scale.</p>
<p>The log-precision fitness measures precision(T) = log₂(2T+1), which grows logarithmically. The rate d(precision)/d(log T) is constant: log₂(10) ≈ 3.32 bits per decade. The constant rate is the integrated form of the second-order rate law. The convergence-aware fitness asks a first-order question: “is error shrinking between checkpoints?” The log-precision fitness asks a second-order question: “is 1/error growing linearly?” Fewer processes satisfy the second-order criterion. Leibniz is the simplest among them in the minimal terminal set.</p>
</section>
<section id="discovery-fitness-quality-coverage-search-space" class="level2">
<h2 class="anchored" data-anchor-id="discovery-fitness-quality-coverage-search-space">Discovery = Fitness Quality × Coverage / Search Space</h2>
<p>The unifying result across all experiments is consistent with a proportionality: P(discovery) scales with fitness quality times coverage, divided by search space size. We propose this as an organizing principle consistent with the data, not a derived result.</p>
<p><span class="math display">\[P(\text{discovery}) \propto \frac{\text{fitness quality} \times \text{coverage}}{\text{search space size}}\]</span></p>
<p>Fitness quality is fixed: the log-precision fitness correctly identifies Leibniz as optimal in all tested configurations. Improving the fitness function, through extended checkpoints, gradient-based selection, or rate consistency penalties, does not improve discovery rates at 15 terminals. The gradient-based selection variant minimized the gradient norm across fitness dimensions (precision, monotonicity, rate, and parsimony balance). It selected for expressions where perturbing the tree produced the smallest change across all dimensions. It produced 0/5 discovery at 15 terminals. That failure confirmed the coverage diagnosis: the fitness landscape was not the bottleneck, the correct building blocks were absent from the population.</p>
<p>Coverage increases with population size, but the relationship is not simple. <span class="citation" data-cites="Sastry2005PopulationSizing">Sastry (<a href="#ref-Sastry2005PopulationSizing" role="doc-biblioref">2005</a>)</span> derived a population-sizing relationship for GP from building-block decision-making theory. The required population grows with the number of building blocks that must be simultaneously present and the difficulty of distinguishing them under selection. Search space scales combinatorially with terminal count: adding one terminal multiplies the number of distinct expressions at each tree size. The space grows much faster than coverage.</p>
<p>The phase transition occurs where the coverage-to-search-space ratio drops below the critical threshold. Below it, the correct building blocks rarely appear in the initial population and rarely survive long enough for selection to assemble them. The scaling grid confirms this quantitatively: the t=10 boundary holds across all tested population sizes, and larger populations produce only marginal improvements at t=6 and t=8. Our population range (1,000 to 10,000) does not reach the scales tested in some GP studies. The sharpness of the transition between t=8 and t=10, holding across a 10x population range, suggests the bottleneck is structural rather than computational.</p>
</section>
<section id="the-confabulation-analogy" class="level2">
<h2 class="anchored" data-anchor-id="the-confabulation-analogy">The Confabulation Analogy</h2>
<p>The project uses wrong-limit attractors as an analogy for confabulation in language models: outputs that appear correct within a finite evaluation horizon but fail under asymptotic scrutiny.</p>
<p><em>Non-GP approaches.</em> Preliminary experiments with reinforcement learning and ant colony optimization (not reported here) produced outputs that pattern-matched to convergence behavior but diverged under extended evaluation. This failure mode is analogous to confabulation.</p>
<p><em>GP with convergence-aware fitness.</em> This produced miscalibration: outputs that approached a plausible value and stopped improving. The behavior is analogous to a model that gives a confident answer without the capacity for further refinement.</p>
<p><em>Leibniz.</em> This exhibits sustained refinement: precision improves at a constant rate without bound, never plateauing, each term contributing a measurable correction. The open-ended precision gain is the series-domain analog of a model that continues to incorporate new evidence without converging prematurely.</p>
<p>A language model that generates a plausible citation to a paper that does not exist exhibits the same structure. The output is locally consistent within the generation horizon (correct formatting, topically relevant author names, reasonable year) but false under verification. The generated citation is a wrong-limit attractor in text space.</p>
<p>The analogy is imperfect but productive. Both phenomena arise from optimization against finite evaluation: a fitness function or loss function that rewards local plausibility without the capacity to verify global correctness. The remedy in both cases is not better loss functions but better questions, evaluating process properties (sustained improvement, calibration) rather than output properties (proximity to a target).</p>
</section>
<section id="implications-for-symbolic-regression" class="level2">
<h2 class="anchored" data-anchor-id="implications-for-symbolic-regression">Implications for Symbolic Regression</h2>
<p>Three findings extend beyond the Leibniz problem, each pointing toward a different aspect of fitness-guided search over infinite-horizon processes.</p>
<p><em>Process-level fitness design.</em> Standard symbolic regression evaluates pointwise accuracy. For problems involving infinite-horizon behavior, such as convergence, stability, or asymptotic scaling, process-level fitness functions that evaluate behavior across evaluation depths may be necessary. The log-precision approach demonstrated here is one such instantiation.</p>
<p><em>Wrong-limit attractors are a distinct failure mode.</em> They are not bloat: they are simpler than the correct answer. They are not overfitting: they genuinely converge. They are not fitness function errors: the fitness ranks them correctly when the correct answer is present. They are coverage failures exploiting the evaluation horizon, and they require a different diagnosis and response than the failure modes typically discussed in symbolic regression.</p>
<p><em>The evaluation horizon trap is fundamental.</em> Any finite evaluation horizon creates exploitable wrong-limit attractors. This constraint applies to any fitness-guided search over infinite-horizon processes, not just GP-based symbolic regression. Extending the horizon shifts the attractor landscape but does not eliminate it.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Constrain the search space to the primitives that matter. With four terminals, discovery was reliable: 19 of 20 seeds found Leibniz across all population sizes (log-precision fitness). With fifteen at populations up to 5,000, none did. At 10x population, an anomalous partial recovery appeared at t=15 (2/5 seeds) but not at t=10, t=12, or t=20. The fitness function still ranked Leibniz as optimal. The algorithm still ran. Irrelevant primitives drowned out the signal.</p>
<p>No fitness modification fixed this. Not log-precision, not convergence-aware, not gradient-based, not extended checkpoints, not heavier penalties. Parsimony pressure (λ_p, a size penalty on expression trees), the evolutionary equivalent of regularization, could not compensate either. Above a narrow threshold it collapsed the population to trivial solutions rather than driving it toward compact correct ones. The fitness was never the bottleneck. The search space was.</p>
<p>This is not specific to genetic programming. A specific prompt constrains an LLM’s search space, fewer plausible-looking wrong answers survive the completion process. Curating training data removes irrelevant primitives before the search begins. In both cases, the intervention that works is not a better objective function or more compute but a smaller, cleaner space of candidates. Our scaling grid is a controlled demonstration: same algorithm, same fitness, same target, success or failure determined entirely by how much irrelevant material is in the search space.</p>
<p>Three directions address the coverage bottleneck within GP. First, building block initialization that seeds structural vocabulary rather than complete answers. Second, automated terminal pruning that discards irrelevant primitives before the full search. Third, island migration that lets successful subpopulations share building blocks. Each attacks the constraint our experiments identify as primary: not the quality of the search, but the quality of the search space.</p>
<p>Beyond GP, the wrong-limit attractor framework suggests evaluation protocols for other finite-horizon systems. In reinforcement learning, testing whether learned policies exhibit sustained improvement under extended episodes, rather than only measuring terminal reward, would detect reward-hacking analogs of the attractors we document here.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Abdusalamov2023Asymptotic" class="csl-entry" role="listitem">
Abdusalamov, R., Kaplunov, J., &amp; Itskov, M. (2023). Discovering asymptotic expansions for problems in mechanics using symbolic regression. <em>Mechanics Research Communications</em>, <em>133</em>, 104197. <a href="https://doi.org/10.1016/j.mechrescom.2023.104197">https://doi.org/10.1016/j.mechrescom.2023.104197</a>
</div>
<div id="ref-Amodei2016ConcreteProblems" class="csl-entry" role="listitem">
Amodei, D., Olah, C., Steinhardt, J., Christiano, P., Schulman, J., &amp; Mané, D. (2016). Concrete problems in <span>AI</span> safety. <em>arXiv Preprint arXiv:1606.06565</em>. <a href="https://arxiv.org/abs/1606.06565">https://arxiv.org/abs/1606.06565</a>
</div>
<div id="ref-NIST2024AI600" class="csl-entry" role="listitem">
<em>Artificial intelligence risk management framework: Generative artificial intelligence profile</em> (NIST AI 600-1). (2024). National Institute of Standards; Technology. <a href="https://doi.org/10.6028/NIST.AI.600-1">https://doi.org/10.6028/NIST.AI.600-1</a>
</div>
<div id="ref-Cranmer2023PySR" class="csl-entry" role="listitem">
Cranmer, M. (2023). Interpretable machine learning for science with <span>PySR</span> and <span class="nocase">SymbolicRegression.jl</span>. <em>arXiv Preprint arXiv:2305.01582</em>. <a href="https://arxiv.org/abs/2305.01582">https://arxiv.org/abs/2305.01582</a>
</div>
<div id="ref-Deb1993Deceptive" class="csl-entry" role="listitem">
Deb, K., &amp; Goldberg, D. E. (1993). Analyzing deception in trap functions. <em>Foundations of Genetic Algorithms</em>, <em>2</em>, 93–108.
</div>
<div id="ref-Goldberg1989GA" class="csl-entry" role="listitem">
Goldberg, D. E. (1989). <em>Genetic algorithms in search, optimization and machine learning</em>. Addison-Wesley.
</div>
<div id="ref-Hillar2012Comment" class="csl-entry" role="listitem">
Hillar, C., &amp; Sommer, F. (2012). Comment on the article <span>“distilling free-form natural laws from experimental data.”</span> <em>arXiv Preprint arXiv:1210.7273</em>. <a href="https://arxiv.org/abs/1210.7273">https://arxiv.org/abs/1210.7273</a>
</div>
<div id="ref-Ji2023Hallucination" class="csl-entry" role="listitem">
Ji, Z., Lee, N., Frieske, R., Yu, T., Su, D., Xu, Y., Ishii, E., Bang, Y. J., Madotto, A., &amp; Fung, P. (2023). Survey of hallucination in natural language generation. <em>ACM Computing Surveys</em>, <em>55</em>(12), 248. <a href="https://doi.org/10.1145/3571730">https://doi.org/10.1145/3571730</a>
</div>
<div id="ref-Jiang2025EGGSR" class="csl-entry" role="listitem">
Jiang, N., Wang, Z., &amp; Xue, Y. (2025). <span>EGG-SR</span>: Embedding symbolic equivalence into symbolic regression via equality graph. <em>arXiv Preprint arXiv:2511.05849</em>. <a href="https://arxiv.org/abs/2511.05849">https://arxiv.org/abs/2511.05849</a>
</div>
<div id="ref-Kamienny2023MCTS" class="csl-entry" role="listitem">
Kamienny, P.-A., Lample, G., Lamprier, S., &amp; Virgolin, M. (2023). Deep generative symbolic regression with <span>Monte-Carlo-Tree-Search</span>. <em>Proceedings of the 40th International Conference on Machine Learning (ICML)</em>, 15655–15668.
</div>
<div id="ref-Li2023GFlowNet" class="csl-entry" role="listitem">
Li, S., Marinescu, I., &amp; Musslick, S. (2023). <span>GFN-SR</span>: Symbolic regression with generative flow networks. <em>NeurIPS 2023 AI for Science Workshop</em>. <a href="https://arxiv.org/abs/2312.00396">https://arxiv.org/abs/2312.00396</a>
</div>
<div id="ref-Poli2008FieldGuide" class="csl-entry" role="listitem">
Poli, R., Langdon, W. B., &amp; McPhee, N. F. (2008a). <em>A field guide to genetic programming</em>. Lulu Enterprises.
</div>
<div id="ref-Poli2008ParsimonyEasy" class="csl-entry" role="listitem">
Poli, R., Langdon, W. B., &amp; McPhee, N. F. (2008b). Parsimony pressure made easy. <em>Proceedings of the 10th Annual Conference on Genetic and Evolutionary Computation (GECCO 2008)</em>, 1267–1274. <a href="https://doi.org/10.1145/1389095.1389340">https://doi.org/10.1145/1389095.1389340</a>
</div>
<div id="ref-Sastry2005PopulationSizing" class="csl-entry" role="listitem">
Sastry, K. (2005). Population sizing for genetic programming based upon decision making. <em>arXiv Preprint Cs/0502020</em>. <a href="https://arxiv.org/abs/cs/0502020">https://arxiv.org/abs/cs/0502020</a>
</div>
<div id="ref-Schmidt2009Distilling" class="csl-entry" role="listitem">
Schmidt, M., &amp; Lipson, H. (2009). Distilling free-form natural laws from experimental data. <em>Science</em>, <em>324</em>(5923), 81–85. <a href="https://doi.org/10.1126/science.1165893">https://doi.org/10.1126/science.1165893</a>
</div>
<div id="ref-Shojaee2023TPSR" class="csl-entry" role="listitem">
Shojaee, P., Meidani, K., Barati Farimani, A., &amp; Reddy, C. (2023). Transformer-based planning for symbolic regression. <em>Advances in Neural Information Processing Systems 36 (NeurIPS)</em>, 45907–45919.
</div>
<div id="ref-Soule1998CodeGrowth" class="csl-entry" role="listitem">
Soule, T., &amp; Foster, J. A. (1998). Effects of code growth and parsimony pressure on populations in genetic programming. <em>Evolutionary Computation</em>, <em>6</em>(4), 293–309. <a href="https://doi.org/10.1162/evco.1998.6.4.293">https://doi.org/10.1162/evco.1998.6.4.293</a>
</div>
<div id="ref-Valipour2021SymbolicGPT" class="csl-entry" role="listitem">
Valipour, M., You, B., Panju, M., &amp; Ghodsi, A. (2021). <span>SymbolicGPT</span>: A generative transformer model for symbolic regression. <em>arXiv Preprint arXiv:2106.14131</em>. <a href="https://arxiv.org/abs/2106.14131">https://arxiv.org/abs/2106.14131</a>
</div>
</div>
</section>
<section id="appendix-a-expression-catalog" class="level1 unnumbered">
<h1 class="unnumbered">Appendix A: Expression Catalog</h1>
<p>This appendix documents all Leibniz-equivalent expressions discovered across 52 experiment files, alongside the most notable wrong-limit attractors. The full machine-readable catalog is in <code>paper/expression_catalog.json</code> (260 records; 52 Leibniz-equivalent, 179 wrong-limit attractors, 29 trivial).</p>
<section id="leibniz-equivalent-expressions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="leibniz-equivalent-expressions">Leibniz-Equivalent Expressions</h2>
<p>All 52 expressions below verified equivalent to (-1)^k / (2k+1) at k=100,000 with zero divergence. Sympy simplification confirms every raw form reduces to -1/(2*k+1), which equals (-1)^k/(2k+1) up to the sign convention absorbed into the alternating factor. The canonical 9-node form appears in 42 of 52 cases; remaining 10 cases carry one extra negation node.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 24%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Seed</th>
<th>Raw Form</th>
<th>Nodes</th>
<th>Fitness</th>
<th>Fitness Function</th>
<th>t</th>
<th>Pop</th>
<th>Experiment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>42</td>
<td><code>((-(-1 ^ k)) / ((-k) - (k - -1)))</code></td>
<td>9</td>
<td>0.01102</td>
<td>log-precision</td>
<td>4</td>
<td>1000</td>
<td>scaling_heatmap_t4_p1000</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-(-1 ^ k)) / ((-1 - k) - k))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>4</td>
<td>1000</td>
<td>scaling_heatmap_t4_p1000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-(-1 ^ k)) / ((-1 - k) - k))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>4</td>
<td>1000</td>
<td>scaling_heatmap_t4_p1000</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-1 ^ k) / (k + (1 + k)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>1000</td>
<td>scaling_heatmap_t4_p1000</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>((-1 ^ k) / ((k * 2) - -1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>1000</td>
<td>scaling_heatmap_t4_p1000</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>((-1 ^ k) / (k + (k - -1)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>2000</td>
<td>scaling_heatmap_t4_p2000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / (1 + (k * 2)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>2000</td>
<td>scaling_heatmap_t4_p2000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-1 ^ k) / ((k - -1) + k))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>2000</td>
<td>scaling_heatmap_t4_p2000</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>(((1 + (k + k)) * (-1 ^ k)) ^ -1)</code></td>
<td>11</td>
<td>0.01102</td>
<td>log-precision</td>
<td>4</td>
<td>2000</td>
<td>scaling_heatmap_t4_p2000</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>((-1 ^ k) / (k - (-1 - k)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>5000</td>
<td>gp_scaling_t4_p5000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / (k - (-1 - k)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>5000</td>
<td>gp_scaling_t4_p5000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-1 ^ k) / ((k * 2) - -1))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>5000</td>
<td>gp_scaling_t4_p5000</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>((-1 ^ k) / (1 + (k + k)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>5000</td>
<td>gp_scaling_t4_p5000</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>5000</td>
<td>scaling_heatmap_t4_p5000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / ((k * 2) - -1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>5000</td>
<td>scaling_heatmap_t4_p5000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-1 ^ k) / ((k * 2) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>5000</td>
<td>scaling_heatmap_t4_p5000</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>((-1 ^ k) / (k - (-1 - k)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>5000</td>
<td>scaling_heatmap_t4_p5000</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>((-1 ^ k) / (k - (-1 - k)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>5000</td>
<td>scaling_heatmap_t4_p5000</td>
</tr>
<tr class="odd">
<td>42</td>
<td><code>((-1 ^ k) / (k + (1 + k)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>10000</td>
<td>gp_scaling_t4_p10000</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-1 ^ k) / ((k + k) - -1))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>10000</td>
<td>gp_scaling_t4_p10000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / ((2 * k) - -1))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>10000</td>
<td>gp_scaling_t4_p10000</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-1 ^ k) / ((k + 1) + k))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>10000</td>
<td>gp_scaling_t4_p10000</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>((-1 ^ k) / ((2 * k) - -1))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>4</td>
<td>10000</td>
<td>gp_scaling_t4_p10000</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>((-1 ^ k) / (1 + (2 * k)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>10000</td>
<td>scaling_heatmap_t4_p10000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / ((2 * k) - -1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>10000</td>
<td>scaling_heatmap_t4_p10000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-1 ^ k) / (1 + (k * 2)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>4</td>
<td>10000</td>
<td>scaling_heatmap_t4_p10000</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>((-(-1 ^ k)) / (-1 - (k + k)))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>4</td>
<td>10000</td>
<td>scaling_heatmap_t4_p10000</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>(-((-1 ^ k) / (-1 - (k + k))))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>4</td>
<td>10000</td>
<td>scaling_heatmap_t4_p10000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / (k - (-1 - k)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>6</td>
<td>1000</td>
<td>scaling_heatmap_t6_p1000</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>((-1 ^ k) / (k + (k + 1)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>6</td>
<td>2000</td>
<td>scaling_heatmap_t6_p2000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / (1 + (k * 2)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>6</td>
<td>2000</td>
<td>scaling_heatmap_t6_p2000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-(-1 ^ k)) / (-1 - (k * 2)))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>6</td>
<td>5000</td>
<td>scaling_heatmap_t6_p5000</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>((-1 ^ k) / ((k + 1) + k))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>6</td>
<td>5000</td>
<td>gp_scaling_t6_p5000</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-1 ^ k) / (1 - (k * -2)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>6</td>
<td>10000</td>
<td>gp_scaling_t6_p10000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / ((k + k) + 1))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>6</td>
<td>10000</td>
<td>gp_scaling_t6_p10000</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-1 ^ k) / (k + (k + 1)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>6</td>
<td>10000</td>
<td>gp_scaling_t6_p10000</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>((-1 ^ k) / ((k - -1) + k))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>6</td>
<td>10000</td>
<td>gp_scaling_t6_p10000</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>((-1 ^ k) / ((2 * k) - -1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>6</td>
<td>10000</td>
<td>scaling_heatmap_t6_p10000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / (k - (-(1 + k))))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>8</td>
<td>1000</td>
<td>scaling_heatmap_t8_p1000</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-1 ^ k) / (k + (k + 1)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>8</td>
<td>2000</td>
<td>scaling_heatmap_t8_p2000</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>((-1 ^ k) / (-(-1 - (k + k))))</code></td>
<td>10</td>
<td>0.01602</td>
<td>log-precision</td>
<td>8</td>
<td>5000</td>
<td>scaling_heatmap_t8_p5000</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-1 ^ k) / ((1 + k) + k))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>10</td>
<td>5000</td>
<td>gp_extended_t10_p5000</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>((-1 ^ k) / ((1 + k) + k))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>10</td>
<td>5000</td>
<td>gp_scaling_t10_p5000</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>((-1 ^ k) / (k + (k + 1)))</code></td>
<td>9</td>
<td>-0.00130</td>
<td>convergence-aware</td>
<td>15</td>
<td>5000</td>
<td>gp_scaling_t15_p5000</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / (1 + (k * 2)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>15</td>
<td>10000</td>
<td>scaling_heatmap_t15_p10000</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-1 ^ k) / (1 + (k * 2)))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>15</td>
<td>10000</td>
<td>scaling_heatmap_t15_p10000</td>
</tr>
<tr class="odd">
<td>42</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>~42</td>
<td>1000</td>
<td>entropy_v1_wide</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>~42</td>
<td>1000</td>
<td>entropy_v1_wide</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>~42</td>
<td>1000</td>
<td>entropy_v1_wide</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>~42</td>
<td>1000</td>
<td>entropy_v1_wide</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>((-1 ^ k) / ((2 * k) + 1))</code></td>
<td>9</td>
<td>0.02102</td>
<td>log-precision</td>
<td>~42</td>
<td>1000</td>
<td>entropy_v1_wide</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>(-1 / (((-1 - k) - k) / (-1 ^ k)))</code></td>
<td>11</td>
<td>0.01102</td>
<td>log-precision</td>
<td>~4</td>
<td>1000</td>
<td>fitness_approach2_w0.1</td>
</tr>
</tbody>
</table>
<p>Note: entropy_v1_wide (v2-era experiment) used a 42-terminal set and injected Leibniz at generation 0. Results are valid as “recognition” tests but not as discovery tests. See Section 4 for the injection confound. The fitness_approach2_w0.1 experiment used the minimal terminal set with a modified log-precision weight.</p>
</section>
<section id="notable-wrong-limit-attractors" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="notable-wrong-limit-attractors">Notable Wrong-Limit Attractors</h2>
<p>The table shows the 10 highest-fitness wrong-limit attractors plus the canonical <code>5/((6+4k)(k-2))</code> attractor from the stress test. Section A.2.1 discusses the canonical attractor in detail.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Seed</th>
<th>Raw Form</th>
<th>Nodes</th>
<th>Fitness</th>
<th>t</th>
<th>Experiment</th>
<th>Simplified</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>31415</td>
<td><code>(((-1 ^ k) * (-k)) / ((1 / 2) - (-k)))</code></td>
<td>13</td>
<td>0.00877</td>
<td>4</td>
<td>scaling_heatmap_t4_p2000</td>
<td><code>-2k(-1)^k/(2k+1)</code></td>
<td>Grandi-Leibniz: S(T)=L(T)-G(T)</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>(-3 / ((7 + k) * (k + -3)))</code></td>
<td>9</td>
<td>0.0232</td>
<td>15</td>
<td>scaling_heatmap_t15_p2000</td>
<td><code>-3/((k-3)(k+7))</code></td>
<td>Partial fraction near pi/4</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>(((-1 / (k ^ 10)) ^ k) * (7 ^ 7))</code></td>
<td>11</td>
<td>0.0230</td>
<td>20</td>
<td>scaling_heatmap_t20_p1000</td>
<td><code>823543*(-1/k^10)^k</code></td>
<td>Decaying oscillation times constant</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>((7 ^ 7) * ((-(k ^ 10)) ^ (-k)))</code></td>
<td>9</td>
<td>0.0230</td>
<td>20</td>
<td>scaling_heatmap_t20_p2000</td>
<td><code>823543/(-k^10)^k</code></td>
<td>Variant of above</td>
</tr>
<tr class="odd">
<td>42</td>
<td><code>(((k - 4) / -4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p10000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>(((k + -4) / -4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p10000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>(((k - 4) / -4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p10000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>(((4 - k) / 4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p1000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>(((-4 + k) / -4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p2000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>((-4 / (k - 4)) ^ 9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p2000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="odd">
<td>42</td>
<td><code>(((k + -4) / -4) ^ -9)</code></td>
<td>7</td>
<td>0.0157</td>
<td>20</td>
<td>scaling_heatmap_t20_p5000</td>
<td><code>-262144/(k-4)^9</code></td>
<td>Power-law decay family</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>(5 / (((1 + 5) + (k * 4)) * (k + -2)))</code></td>
<td>13</td>
<td>0.0073</td>
<td>15</td>
<td>stress_L1</td>
<td><code>5/(2(k-2)(2k+3))</code></td>
<td>Canonical 5/((6+4k)(k-2)) attractor</td>
</tr>
</tbody>
</table>
<section id="the-564kk-2-attractor" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-564kk-2-attractor">The 5/((6+4k)(k-2)) Attractor</h3>
<p>The expression <code>5/((6+4k)(k-2))</code> found by seed 42 in the stress test (15-terminal set) achieves 15.93 bits of precision at T=10,000, exceeding Leibniz’s 15.29 bits. The 5/((6+4k)(k-2)) expression is the clearest example of the evaluation horizon trap in the dataset.</p>
<p>The partial sum of this series converges, but to a limit different from pi/4. Within the evaluation horizon (T up to 10,000), the convergence curve is steeper than Leibniz’s. The log-precision fitness assigns it a higher raw information score: 15.93 bits versus 15.29 bits. The attractor’s mean rate is ~4.31 bits/decade versus 3.32 bits/decade for Leibniz. Leibniz wins under the full fitness only because parsimony penalizes the 13-node attractor against the 9-node Leibniz form.</p>
<p>The narrow margin shows the fitness function correctly ranks Leibniz above the attractor when both are present. The failure at 15 terminals is a coverage failure, not a fitness landscape failure. The 15-terminal search space is large enough that strong attractors appear before Leibniz building blocks assemble.</p>
</section>
<section id="power-law-decay-family-t20" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="power-law-decay-family-t20">Power-Law Decay Family (t=20)</h3>
<p>At t=20 with log-precision fitness, the dominant attractor family is <code>((k-4)/(-4))^-9</code> and variants. This expression has 7 nodes and converges monotonically to zero, not pi/4. Within the evaluation horizon, its partial-sum curve looks like rapid convergence to a small positive constant. All five seeds at pop=10000 converged to this family. The power-law attractor dominated before Leibniz building blocks could be assembled in the 20-terminal search space.</p>
</section>
<section id="the-grandi-leibniz-attractor-t4-seed31415" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-grandi-leibniz-attractor-t4-seed31415">The Grandi-Leibniz Attractor (t=4, seed=31415)</h3>
<p>The most structurally interesting wrong-limit attractor in the dataset is <code>(((-1 ^ k) * (-k)) / ((1 / 2) - (-k)))</code>, found by seed 31415 at t=4 and pop=2000. The expression has 13 nodes and fitness 0.00877 under the log-precision function. The GP discovered this expression from random initialization; no Leibniz encoding was present.</p>
<p>Sympy reduces the raw form to <code>-2k(-1)^k / (2k+1)</code>. Factoring yields:</p>
<pre><code>-2k / (2k+1) = -(2k+1-1) / (2k+1) = -1 + 1/(2k+1)</code></pre>
<p>Multiplying by <code>(-1)^k</code> gives the k-th term as <code>-(-1)^k + (-1)^k/(2k+1)</code>. The partial sum decomposes as:</p>
<pre><code>S(T) = L(T) - G(T)</code></pre>
<p>where L(T) = sum_{k=0}^{T-1} (-1)^k / (2k+1) is the Leibniz partial sum and G(T) = sum_{k=0}^{T-1} (-1)^k is the Grandi partial sum. G(T) equals 0 at even T and 1 at odd T.</p>
<p>We verified this computationally. At T=10, 20, 50, 100, 1000, S(T) = L(T) to machine precision. At T=5, S(5) = L(5) - 1, giving an error of approximately 0.95 relative to pi/4.</p>
<p>The series does not converge in the standard sense. Even-indexed partial sums converge to pi/4; odd-indexed partial sums converge to pi/4 - 1.</p>
<p>The log-precision fitness uses 11 checkpoints at T = {5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000}. We counted 1 odd checkpoint (T=5) and 10 even checkpoints. At every even checkpoint, S(T) = L(T) exactly, so the attractor’s precision profile is indistinguishable from Leibniz’s at 10 of 11 evaluation points.</p>
<p>The single odd checkpoint (T=5) records 0.0733 bits of precision, far below Leibniz’s 4.34 bits at the same depth. But this low baseline raises the apparent mean precision gain rate to 4.609 bits/decade, above Leibniz’s 3.32 bits/decade. The fitness simultaneously penalizes T=5 and rewards the elevated rate, leaving the attractor at a lower fitness (0.00877) than Leibniz (0.02102). The 10-of-11 checkpoint alignment made the attractor competitive enough to dominate this run.</p>
<p>The Grandi-Leibniz attractor is the most direct instance of the evaluation horizon trap in the dataset. The trap exploits not just the finiteness of the evaluation horizon but the specific parity structure of the checkpoint grid. A checkpoint grid with more odd values would have identified the divergence immediately.</p>
</section>
</section>
<section id="expressions-by-terminal-count" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="expressions-by-terminal-count">Expressions by Terminal Count</h2>
<section id="t4-minimal-terminal-set" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="t4-minimal-terminal-set">t=4 (Minimal Terminal Set)</h3>
<p>With four terminals {k, 1, -1, 2}, (-1)^k is the only oscillating structure constructible from the available primitives. This makes the fitness landscape nearly unimodal: the single basin of attraction corresponds to Leibniz variants. We found 28 of 30 seeds (93%) discovered Leibniz-equivalent expressions across the two t=4 population sweeps. Two t=4 seeds from scaling_heatmap_t4_p2000 failed; Section A.2.3 covers seed 31415’s anomalous result in detail.</p>
<p>All 28 successful t=4 expressions simplify to -1/(2k+1) under sympy. Node count is 9 in 21 cases and 10 or 11 in the remaining 7 cases, reflecting how many negation nodes the GP included in the final tree.</p>
</section>
<section id="t6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="t6">t=6</h3>
<p>With six terminals, the search space expands but (-1)^k remains the easiest oscillating structure. We found 10 of 30 seeds (33%) discovered Leibniz across the t=6 population and fitness-function sweep. Log-precision fitness found Leibniz at pop=1000 (1 seed) and pop=2000 (2 seeds). Both fitness functions succeeded at pop=10000: 4 seeds convergence-aware, 1 seed log-precision, plus 1 seed log-precision at pop=5000. The remaining 20 seeds converged to wrong-limit attractors. The dominant family was rational expressions with a pole near k=0 or small constants.</p>
</section>
<section id="t8" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="t8">t=8</h3>
<p>Only 3 of 30 seeds (10%) discovered Leibniz at t=8, all from the log-precision fitness. The dominant wrong-limit attractor at t=8 is <code>((4-((4--3)^-2) - k/(-3))^-2)</code> and its variants, appearing in 8 of 30 seeds. This attractor achieves ~20.66 bits of precision at T=10,000, roughly 5 bits better than Leibniz’s 15.29 bits at the same horizon. At pop=10000, 0/5 seeds found Leibniz while smaller populations each found 1/5. Larger populations find strong attractors faster, which illustrates the population inversion effect.</p>
</section>
<section id="t10-failure-regime" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="t10-failure-regime">t&gt;=10 (Failure Regime)</h3>
<p>We found 5 Leibniz-equivalent expressions at t&gt;=10, all anomalous. Two appeared at t=10 with convergence-aware fitness (same seed 7 in two overlapping experiments). One appeared at t=15 with convergence-aware fitness (seed 137, pop=5000). Two appeared at t=15 with log-precision fitness (seeds 137 and 2718, pop=10000). No expressions were found at t=12 or t=20.</p>
<p>The t=10 and t=15 discoveries are consistent with lucky initializations rather than systematic search. At t=10, seed 7 appears twice because <code>gp_extended_t10_p5000</code> and <code>gp_scaling_t10_p5000</code> ran the same seed with the same engine. Both found <code>((-1 ^ k) / ((1 + k) + k))</code>. The t=15/p=10000 result (2/5 seeds) is discussed in Section 5.</p>
</section>
</section>
<section id="trivial-and-parsimony-collapsed-expressions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="trivial-and-parsimony-collapsed-expressions">Trivial and Parsimony-Collapsed Expressions</h2>
<p>Several experimental conditions produced trivial expressions: either the constant zero or small numerical constants with no k dependence. These appeared primarily in three contexts.</p>
<p>The fitness_approach1 and fitness_approach4 experiments each produced zero (0) as the best expression for all five seeds. Approach B (gradient uniformity bonus) amplified the zero constant because a constant expression achieves near-perfect uniformity under mutation, trivially satisfying the gradient-uniformity objective. Approach D (gradient magnitude negated) similarly found the flattest point in the fitness landscape.</p>
<p>The stress_L1 file (15-terminal set, single stress level) produced zero in two of five seeds, the canonical 5/((6+4k)(k-2)) attractor in one seed, and small rational constants in the remaining two seeds. None found Leibniz. The 15-terminal failure persists across fitness formulations tested here, confirming it is not specific to the original log-precision fitness.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 21%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 6%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Seed</th>
<th>Raw Form</th>
<th>Nodes</th>
<th>Fitness</th>
<th>t</th>
<th>Experiment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>42</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach1</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach1</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach1</td>
</tr>
<tr class="even">
<td>2718</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach1</td>
</tr>
<tr class="odd">
<td>31415</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach1</td>
</tr>
<tr class="even">
<td>42</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach4</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach4</td>
</tr>
<tr class="even">
<td>137</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach4</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach4</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>n/a</td>
<td>fitness_approach4</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>15</td>
<td>stress_L1</td>
</tr>
<tr class="even">
<td>31415</td>
<td><code>0</code></td>
<td>1</td>
<td>-0.00486</td>
<td>15</td>
<td>stress_L1</td>
</tr>
<tr class="odd">
<td>137</td>
<td><code>((-5 ^ -5) / -4)</code></td>
<td>5</td>
<td>-0.00411</td>
<td>15</td>
<td>stress_L1</td>
</tr>
<tr class="even">
<td>7</td>
<td><code>((-5 ^ -5) / -4)</code></td>
<td>5</td>
<td>-0.00558</td>
<td>n/a</td>
<td>fitness_approach2_w0.1</td>
</tr>
<tr class="odd">
<td>2718</td>
<td><code>(4 / ((3 * -5) ^ 4))</code></td>
<td>7</td>
<td>-0.01098</td>
<td>n/a</td>
<td>fitness_approach2_w0.1</td>
</tr>
</tbody>
</table>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>